name: X scheduler

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run scheduler
        env:
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          REFRESH_TOKEN_ACC1: ${{ secrets.REFRESH_TOKEN_ACC1 }}
          REFRESH_TOKEN_ACC2: ${{ secrets.REFRESH_TOKEN_ACC2 }}
          REFRESH_TOKEN_ACC3: ${{ secrets.REFRESH_TOKEN_ACC3 }}
          ACCOUNTS_JSON: ${{ vars.ACCOUNTS_JSON }}
          CSV_FILE: ${{ vars.CSV_FILE }}
          STATE_FILE: ${{ vars.STATE_FILE }}
          WINDOW_MIN: ${{ vars.WINDOW_MIN }}
        run: |
          python post_scheduler.py
