name: X metrics

on:
  schedule:
    - cron: "0 12 */2 * *"   # cada 2 días a las 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Node.js (para cifrar secrets)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
          npm i tweetsodium

      - name: Run metrics
        env:
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          REFRESH_TOKEN_ACC1: ${{ secrets.REFRESH_TOKEN_ACC1 }}
          REFRESH_TOKEN_ACC2: ${{ secrets.REFRESH_TOKEN_ACC2 }}
          REFRESH_TOKEN_ACC3: ${{ secrets.REFRESH_TOKEN_ACC3 }}
          ACCOUNTS_JSON: ${{ vars.ACCOUNTS_JSON }}
          STATE_FILE: ${{ vars.STATE_FILE }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
        run: |
          python metrics_report.py

      - name: Subir artefacto con tokens rotados (backup)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: new-refresh-tokens
          path: .tokens_out.json
          if-no-files-found: ignore
          retention-days: 1

      - name: Rotar refresh tokens en Secrets (seguro)
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_ADMIN_TOKEN }}
          script: |
            const fs = require('fs');
            const sodium = require('tweetsodium');
            const path = '.tokens_out.json';
            if (!fs.existsSync(path)) {
              core.info('No hay tokens nuevos.');
              return;
            }
            const newTokens = JSON.parse(fs.readFileSync(path, 'utf8'));
            const { data: pub } = await github.request('GET /repos/{owner}/{repo}/actions/secrets/public-key', {
              owner: context.repo.owner, repo: context.repo.repo
            });
            for (const [acc, token] of Object.entries(newTokens)) {
              const name = `REFRESH_TOKEN_${acc}`;
              const messageBytes = Buffer.from(token);
              const keyBytes = Buffer.from(pub.key, 'base64');
              const encryptedBytes = sodium.seal(messageBytes, keyBytes);
              const encrypted = Buffer.from(encryptedBytes).toString('base64');
              await github.request('PUT /repos/{owner}/{repo}/actions/secrets/{secret_name}', {
                owner: context.repo.owner, repo: context.repo.repo,
                secret_name: name, encrypted_value: encrypted, key_id: pub.key_id
              });
              core.info(`Rotado secret ${name}`);
            }
